---
title: "Survey Data Analysis"
author: "Jack Luby"
date: "12/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
data <- read_csv('survey_data.csv') %>% 
  slice(3:280)
```

```{r}
stem_concentrations <- c("Applied Mathematics", "Astrophysics", "Biomedical Engineering", "Chemical and Physical Biology", "Chemistry", "Chemistry and Physics", "Computer Science", "Earth and Planetary Sciences", "Electrical Engineering", "Environmental Science and Engineering", "Environmental Science and Public Policy", "Human Developmental and Regenerative Biology", "Human Evolutionary Biology", "Integrative Biology", "Mathematics", "Mechanical Engineering", "Molecular and Cellular Biology", "Neuroscience", "Physics", "Statistics")
order <- c("I attend rarely", "I attend sometimes", "I attend around half the time", "I attend frequently", "I attend very frequently")

data <- data %>% 
  mutate(STEM = "Non-STEM") %>% 
  rename(gender = Q2, year = Q3, house = Q4, international = Q5, athlete = Q6, work_hours = Q9, attend_hours = Q10, concentration = Q11, honors = Q13, office_hours = Q15, study_sessions = Q16, concentration_lunches = Q17, social_events = Q18, other_concentration_social = Q19, satisfaction = Q20)

for (i in stem_concentrations){
  data <- mutate(data, STEM = case_when(str_detect(concentration, i) ~ "STEM",
                                TRUE ~ STEM))
}

data_mod <- data %>% 
  filter(!is.na(Q22)) %>% 
  filter(Q22 != "Prefer not to say") %>% 
  mutate(Q22 = ifelse(Q22 == "Yes", 1, 0)) %>% 
  mutate(STEM = ifelse(STEM == "STEM", 1, 0)) %>% 
  mutate(work_hours = parse_number(work_hours),
         attend_hours = parse_number(attend_hours)) %>% 
  filter(gender %in% c("Male", "Female")) %>% 
  filter(year != "Other (Please specify)") %>% 
  mutate_at(.vars = vars(office_hours,study_sessions,concentration_lunches,social_events), 
            .funs = funs(. = case_when(. == "I attend rarely" ~ 1,
                                       . == "I attend sometimes" ~ 2,
                                       . == "I attend around half the time" ~ 3,
                                       . == "I attend frequently" ~ 4,
                                       . == "I attend very frequently" ~ 5,
                                       TRUE ~ 0))) %>% 
  mutate_at(.vars = vars(office_hours_., study_sessions_., concentration_lunches_., social_events_.), 
            .funs = funs(ifelse(. == 0, 0, 1))) %>% 
  mutate(satisfaction = case_when(satisfaction == "Strongly disagree" ~ 0,
                         satisfaction == "Somewhat disagree" ~ 1,
                         satisfaction == "Neither agree nor disagree" ~ 2,
                         satisfaction == "Somewhat agree" ~ 3,
                         satisfaction == "Strongly agree" ~ 4))
  

 # mutate(hard_worker = case_when(Q9 >= mean(Q9, na.rm = TRUE) + sd(Q9, na.rm = TRUE) ~ 1,
  #                               TRUE ~ 0)) %>% 
 # filter(Q9 >= mean(Q9, na.rm = TRUE) + sd(Q9, na.rm = TRUE) | Q9 <= mean(Q9, na.rm = TRUE) - sd(Q9, na.rm = TRUE))
```

```{r}
library(survey)

survey_data_unweighted <- survey::svydesign(ids = ~1, data = data_mod %>% 
                                              filter(gender %in% c("Male", "Female"),
                                                     year %in% c("First-Year", "Sophomore", "Junior", "Senior"),
                                                     athlete %in% c("Yes", "No")))

gender.dist <- data.frame(gender = c("Male", "Female"),
                       Freq = nrow(data_mod) * c(0.5, 0.5))

year.dist <- data.frame(year = c("First-Year", "Sophomore", "Junior", "Senior"),
                       Freq = nrow(data_mod) * c(.25, .25, .25, .25))

athlete.dist <- data.frame(athlete = c("Yes", "No"),
                       Freq = nrow(data_mod) * c(.2, .8))

data.svy.rake <- rake(design = survey_data_unweighted,
                   sample.margins = list(~gender, ~year, ~athlete),
                   population.margins = list(gender.dist, year.dist, athlete.dist))

View(data_mod %>% select(Q22, STEM))
summary(lm(Q22 ~ (Q2-1) + STEM*(Q2-1) + Q9*(Q2-1) + Q10*(Q2-1), data = data_mod)) # Significant one
summary(svyglm(Q22 ~ STEM + Q10 + Q2 + Q3 + Q5 + Q6, design = data.svy.rake))


summary(svyglm(Q22 ~ gender + year + STEM + attend_hours + work_hours + athlete, design = data.svy.rake))

summary(lm(Q22 ~ gender + year + STEM + work_hours*athlete + attend_hours*athlete + Q15_. + Q16_. + Q17_. + Q18_. + Q20, data = data_mod))
```

```{r}
relationship_sum <- data_mod %>% 
  filter(!is.na(Q22),
         Q22 != "Prefer not to say",
         !is.na(year),
         year != "Other (Please specify)") %>% 
  group_by(Q22, year) %>% 
  summarize(count = n()) %>%
  ungroup() %>% 
  group_by(year) %>% 
  mutate(percentage = round(count/sum(count) * 100, 2)) %>% 
  ungroup() %>% 
  filter(Q22 == "Yes")
  
relationship_sum_general <- data_mod %>% 
  filter(!is.na(Q22),
         Q22 != "Prefer not to say",
         !is.na(year),
         year != "Other (Please specify)") %>% 
  group_by(Q22) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  mutate(percentage = round(count/sum(count) * 100, 2))
  
gender_sum <- data_mod %>% 
  filter(!is.na(gender)) %>% 
  group_by(gender) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  mutate(percentage = round(count/sum(count) * 100, 2))

year_sum <- data_mod %>% 
  filter(!is.na(year),
         year != "Other (Please specify)") %>% 
  group_by(year) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  mutate(percentage = round(count/sum(count) * 100, 2))

athlete_sum <- data_mod %>% 
  filter(!is.na(athlete)) %>% 
  group_by(athlete) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  mutate(percentage = round(count/sum(count) * 100, 2))

STEM_sum <- data_mod %>%
  group_by(STEM) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  mutate(percentage = round(count/sum(count) * 100, 2)) %>% 
  mutate(STEM = ifelse(STEM == 1, "STEM", "Non-STEM"))

work_hist <- ggplot(data, aes(x=as.numeric(work_hours))) + geom_histogram(binwidth = 1)

attend_hist <- ggplot(data, aes(x=as.numeric(attend_hours))) + geom_histogram(binwidth=1)

total_work_hist <- ggplot(data, aes(x=as.numeric(work_hours)+as.numeric(attend_hours))) + geom_histogram(binwidth=5)
attend_hist
```


